#!/bin/bash
env=$1
command=$2
value=$3

bucket=$(cat ~/.kamino/bucket.config)
process_dir=$(pwd)

if [ $value ]; then
	filename=$(basename $value)
else
	command=$1
	value=$2
fi

# Usage
## Kamino [env] command value
## kamino --dev upload /etc/hosts
## kamino --prod clone hosts

function upload(){
	## Files properties
	destination="path: "$(dirname $value)
	
	#######################################
	# Copy to /tmp
	cp -r $value /tmp/${filename}
	echo "$value" > /tmp/path.config
	#######################################	
	cd /tmp
	tar -cvwf ${filename}.tar ${filename} path.config
	cd $process_dir
	######################################
	s3cmd put /tmp/${filename}.tar s3://${bucket}/${env}/${filename}.tar
	s3cmd list s3://${bucket}
	
	# Remove from tpm
	rm -rf /tmp/${filename}
	rm -rf /tmp/${filename}.tar
}

function clone(){
	# Downloading config tar
	s3cmd get s3://${bucket}/${env}/${filename}.tar ${filename}.tar
	# Extract config tar
	tar -xvf ${value}.tar
	# Remove tar
	rm -rf ${value}.tar
	# Destination path
	path=$(cat path.config)
	# Replace current config
	mv -i $value $path
	# Clear downloaded files
	rm -rf path.config
	rm -rf $value
}

function setup(){
	root=$(pwd)
	dna=$1
	echo "Looking for DNA $dna"
	path=${root}/${dna}/install
	if [ -f $path ]; then
		echo "$dna DNA founded"
		echo "Installing $dna DNA"
		bash $path
	else
		echo "$dna DNA not found"
	fi
}

function depends(){
	root=$(pwd)
	dependency=$1
	if [ -z $(which $dependency) ]; then
		echo "Dependency $dependency not installed"
		setup $dependency
	else
		echo "Dependency $dependency is already installed"
	fi
}

function main(){
	$command $value
}

main