#!/bin/bash

# To check the number of arguments use: $#

function status_code(){
	url=$1
	curl -sL -w "%{http_code}" $url -o /dev/null
}

# is_up $url
# Check if the http response status code is different from 000, 404 and 403
function is_up(){
	url=$1
	result=$(status_code $url)

	if [ $result -ne 000 ] && [ $result -ne 404 ] && [ $result -ne 403 ]; then
		echo true
	else
		echo false
	fi
}

# Check if a file or global command is found
function exists(){
	path=$1
	if [ -f $path ] || [ $(which $path) ]; then
		echo true
	else
		echo false
	fi
}

